acme_product_homepage:
    path:     product/hello/{name}
    defaults: { _controller: AcmeProductBundle:Default:index }

acme_product_list:
    path:     products/
    defaults: { _controller: AcmeProductBundle:Default:list, _format: 'json' }
    requirements:
        _method: GET

acme_product_get:
    path:     product/{id}/
    defaults: { _controller: AcmeProductBundle:Default:get, _format: 'json' }
    requirements:
        _method: GET
        id: "\d+"

acme_product_create:
    path:     product/
    defaults: { _controller: AcmeProductBundle:Default:create}
    requirements:
        _method: POST

acme_product_edit:
    path:     product/{id}/
    defaults: { _controller: AcmeProductBundle:Default:edit}
    requirements:
        _method: PUT

acme_product_remove:
    path:     product/{id}/
    defaults: { _controller: AcmeProductBundle:Default:remove}
    requirements:
        _method: DELETE